// fsp_rt.c — Bipedal footstep planner.
//
// Discrete A* search over reachable footstep poses with a user-
// supplied action set and terrain-validity callback. Foundation
// for bipedal locomotion planning where the front-end picks where
// each foot lands and the back-end (e.g., whole-body controller)
// realizes the steps.
//
// State: (x, y, θ, foot ∈ {LEFT=0, RIGHT=1}). Successors are
// generated by applying each registered action — an offset
// (dx, dy, dθ) in the stance foot's frame. The y-component is
// mirrored when the stance foot is the right foot, giving symmetric
// gait patterns from a single action set written in left-foot
// coordinates.
//
// State discretization for A* visited bookkeeping:
//   ix = round(x / res_xy)
//   iy = round(y / res_xy)
//   it = round((θ mod 2π) / res_theta)   (mod n_theta_bins)
//
// Defaults:
//   res_xy        = 0.05 m
//   res_theta     = 5° (π/36 rad)
//   goal_tol_xy   = 0.10 m
//   goal_tol_th   = 10° (π/18 rad)
//
// Goal check: a state qualifies as a goal if its (x, y) is within
// `goal_tol_xy` of the goal AND its θ is within `goal_tol_theta`
// of the goal heading. Either foot can be the final stance foot.
//
// Heuristic: Euclidean distance to goal divided by the maximum
// forward step length over the registered action set (admissible
// when no action exceeds that step length, which is the case for
// any sane bipedal action set).
//
// Limitations (mid-stance trajectories / smoothed gait /
// dynamic stability constraints land in v0.6 if needed):
// - Static (geometric) planning only — no dynamics or ZMP/CoM
//   constraints. The output is a sequence of foot placements, not
//   a feasible whole-body trajectory.
// - Per-step cost = action.cost + Euclidean(prev → next); no
//   per-step terrain cost (would need a separate cost callback).
// - Hash table is capped at 1M slots (open addressing, linear
//   probing). Plenty for typical room-scale plans (< 10k expansions).
//
// Compile: clang -c stdlib/runtime/fsp_rt.c -o target/fsp.obj -O2

#include <stdlib.h>
#include <string.h>
#include <math.h>
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

static double _i2f(long long x) { double d; memcpy(&d, &x, sizeof(double)); return d; }
static long long _f2i(double d) { long long x; memcpy(&x, &d, sizeof(double)); return x; }

typedef long long (*valid_fn_t)(long long x_b, long long y_b, long long theta_b);

typedef struct {
    double dx, dy, dtheta;
    double cost;
} _FSPAction;

typedef struct {
    double x, y, theta;
    int foot;            // 0 = LEFT, 1 = RIGHT
    double g;
    int parent;          // node index of predecessor (-1 for start)
} _FSPNode;

typedef struct {
    long long key;       // -1 if empty
    int node_idx;
    double g;
} _FSPHash;

typedef struct { double f; int node_idx; } _FSPHeapItem;

typedef struct {
    int n_actions, cap_actions;
    _FSPAction *actions;
    double res_xy, res_theta;
    double goal_tol_xy, goal_tol_theta;
    // build state used during plan
    int n_nodes, cap_nodes;
    _FSPNode *nodes;
    int *path;
    int path_len;
} NFSP;

long long nuc_fsp_new(void) {
    NFSP *p = (NFSP *)calloc(1, sizeof(NFSP));
    p->cap_actions = 8;
    p->actions = (_FSPAction *)calloc(p->cap_actions, sizeof(_FSPAction));
    p->res_xy = 0.05;
    p->res_theta = M_PI / 36.0;       // 5 degrees
    p->goal_tol_xy = 0.10;
    p->goal_tol_theta = M_PI / 18.0;  // 10 degrees
    return (long long)(size_t)p;
}

void nuc_fsp_set_resolution(long long h, long long res_xy_b, long long res_theta_b) {
    NFSP *p = (NFSP *)(void *)(size_t)h;
    if (!p) return;
    double rxy = _i2f(res_xy_b), rt = _i2f(res_theta_b);
    if (rxy > 0) p->res_xy = rxy;
    if (rt > 0)  p->res_theta = rt;
}

void nuc_fsp_set_goal_tolerance(long long h, long long tol_xy_b, long long tol_t_b) {
    NFSP *p = (NFSP *)(void *)(size_t)h;
    if (!p) return;
    double txy = _i2f(tol_xy_b), tt = _i2f(tol_t_b);
    if (txy > 0) p->goal_tol_xy = txy;
    if (tt > 0)  p->goal_tol_theta = tt;
}

long long nuc_fsp_add_action(long long h, long long dx_b, long long dy_b,
                              long long dtheta_b, long long cost_b)
{
    NFSP *p = (NFSP *)(void *)(size_t)h;
    if (!p) return -1;
    if (p->n_actions >= p->cap_actions) {
        p->cap_actions *= 2;
        p->actions = (_FSPAction *)realloc(p->actions, p->cap_actions * sizeof(_FSPAction));
    }
    _FSPAction *a = &p->actions[p->n_actions];
    a->dx = _i2f(dx_b); a->dy = _i2f(dy_b);
    a->dtheta = _i2f(dtheta_b);
    a->cost = _i2f(cost_b);
    if (a->cost < 0) a->cost = 0;
    return (long long)(p->n_actions++);
}

// === Min-heap on f-score ===
static void _heap_push(_FSPHeapItem *h, int *sz, double f, int idx) {
    int i = (*sz)++;
    h[i].f = f; h[i].node_idx = idx;
    while (i > 0) {
        int parent = (i - 1) / 2;
        if (h[parent].f > h[i].f) {
            _FSPHeapItem t = h[parent]; h[parent] = h[i]; h[i] = t;
            i = parent;
        } else break;
    }
}
static int _heap_pop(_FSPHeapItem *h, int *sz) {
    if (*sz == 0) return -1;
    int top = h[0].node_idx;
    h[0] = h[--(*sz)];
    int i = 0;
    for (;;) {
        int l = 2*i+1, r = 2*i+2, best = i;
        if (l < *sz && h[l].f < h[best].f) best = l;
        if (r < *sz && h[r].f < h[best].f) best = r;
        if (best != i) {
            _FSPHeapItem t = h[best]; h[best] = h[i]; h[i] = t;
            i = best;
        } else break;
    }
    return top;
}

// === State key + hash ===

// Discretize and pack into a 64-bit key (with foot bit at top).
static long long _state_key(NFSP *p, double x, double y, double theta, int foot) {
    long ix = (long)floor(x / p->res_xy + 0.5);
    long iy = (long)floor(y / p->res_xy + 0.5);
    // Wrap theta into [0, 2π).
    double tw = fmod(theta, 2.0 * M_PI);
    if (tw < 0) tw += 2.0 * M_PI;
    long it = (long)floor(tw / p->res_theta + 0.5);
    long n_theta = (long)floor(2.0 * M_PI / p->res_theta + 0.5);
    if (it >= n_theta) it = 0;
    // Pack: foot (1 bit) | it (12 bits) | iy (24 bits, signed-shifted) | ix (24 bits)
    long iy_shift = iy + (1L << 23);
    long ix_shift = ix + (1L << 23);
    if (iy_shift < 0) iy_shift = 0;
    if (ix_shift < 0) ix_shift = 0;
    if (iy_shift >= (1L << 24)) iy_shift = (1L << 24) - 1;
    if (ix_shift >= (1L << 24)) ix_shift = (1L << 24) - 1;
    long long key = ((long long)foot << 60) |
                    ((long long)it << 48) |
                    ((long long)iy_shift << 24) |
                    ((long long)ix_shift);
    return key;
}

// FNV-like hash of a 64-bit key.
static unsigned _hash_u64(long long key, int cap) {
    unsigned long long k = (unsigned long long)key;
    k ^= k >> 33;
    k *= 0xff51afd7ed558ccdULL;
    k ^= k >> 33;
    k *= 0xc4ceb9fe1a85ec53ULL;
    k ^= k >> 33;
    return (unsigned)(k & (cap - 1));
}

static int _hash_get(_FSPHash *t, int cap, long long key, double *g_out, int *idx_out) {
    unsigned i = _hash_u64(key, cap);
    for (int probe = 0; probe < cap; probe++) {
        if (t[i].key == -1) return 0;
        if (t[i].key == key) { *g_out = t[i].g; *idx_out = t[i].node_idx; return 1; }
        i = (i + 1) & (cap - 1);
    }
    return 0;
}

static void _hash_put(_FSPHash *t, int cap, long long key, double g, int node_idx) {
    unsigned i = _hash_u64(key, cap);
    for (int probe = 0; probe < cap; probe++) {
        if (t[i].key == -1 || t[i].key == key) {
            t[i].key = key; t[i].g = g; t[i].node_idx = node_idx;
            return;
        }
        i = (i + 1) & (cap - 1);
    }
}

// === Plan ===

static double _angle_diff(double a, double b) {
    double d = a - b;
    while (d >  M_PI) d -= 2.0 * M_PI;
    while (d < -M_PI) d += 2.0 * M_PI;
    return d;
}

long long nuc_fsp_plan(long long h,
    long long x0_b, long long y0_b, long long t0_b, long long foot0_,
    long long xg_b, long long yg_b, long long tg_b,
    long long max_iters, long long valid_fp)
{
    NFSP *p = (NFSP *)(void *)(size_t)h;
    if (!p) return 0;
    if (p->n_actions <= 0) return 0;
    valid_fn_t is_valid = (valid_fn_t)(void *)(size_t)valid_fp;
    if (!is_valid) return 0;

    double x0 = _i2f(x0_b), y0 = _i2f(y0_b), t0 = _i2f(t0_b);
    double xg = _i2f(xg_b), yg = _i2f(yg_b), tg = _i2f(tg_b);
    int foot0 = (int)foot0_ & 1;
    int max_it = (int)max_iters;
    if (max_it <= 0) max_it = 100000;

    // Estimate max forward step length for heuristic admissibility.
    double max_step = 0;
    for (int a = 0; a < p->n_actions; a++) {
        _FSPAction *ac = &p->actions[a];
        double s = sqrt(ac->dx * ac->dx + ac->dy * ac->dy);
        if (s > max_step) max_step = s;
    }
    if (max_step < 1e-6) max_step = 1.0;

    // Reset
    if (p->path) { free(p->path); p->path = NULL; }
    p->path_len = 0;
    p->n_nodes = 0;
    if (!p->nodes) {
        p->cap_nodes = 1024;
        p->nodes = (_FSPNode *)malloc(p->cap_nodes * sizeof(_FSPNode));
    }

    // Hash table sized to next pow-2 ≥ 4 × max_iters, capped at 1M.
    int cap = 16;
    while (cap < max_it * 4 && cap < (1 << 20)) cap <<= 1;
    _FSPHash *table = (_FSPHash *)malloc(cap * sizeof(_FSPHash));
    for (int i = 0; i < cap; i++) table[i].key = -1;

    // Heap.
    int heap_cap = max_it * 8 + 16;
    _FSPHeapItem *heap = (_FSPHeapItem *)malloc(heap_cap * sizeof(_FSPHeapItem));
    int heap_size = 0;

    // Push start.
    if (p->n_nodes >= p->cap_nodes) {
        p->cap_nodes *= 2;
        p->nodes = (_FSPNode *)realloc(p->nodes, p->cap_nodes * sizeof(_FSPNode));
    }
    int start_idx = p->n_nodes++;
    _FSPNode *sn = &p->nodes[start_idx];
    sn->x = x0; sn->y = y0; sn->theta = t0; sn->foot = foot0;
    sn->g = 0; sn->parent = -1;
    long long start_key = _state_key(p, x0, y0, t0, foot0);
    _hash_put(table, cap, start_key, 0.0, start_idx);
    double dx0 = xg - x0, dy0 = yg - y0;
    double h0 = sqrt(dx0*dx0 + dy0*dy0) / max_step;
    _heap_push(heap, &heap_size, h0, start_idx);

    int found = 0, goal_idx = -1;
    int expansions = 0;
    while (heap_size > 0 && expansions < max_it) {
        int u = _heap_pop(heap, &heap_size);
        _FSPNode cur = p->nodes[u];   // copy by value (nodes array may realloc)
        expansions++;

        // Goal check.
        double dxg = cur.x - xg, dyg = cur.y - yg;
        if (sqrt(dxg*dxg + dyg*dyg) <= p->goal_tol_xy &&
            fabs(_angle_diff(cur.theta, tg)) <= p->goal_tol_theta)
        {
            found = 1; goal_idx = u; break;
        }

        double cs = cos(cur.theta), sn = sin(cur.theta);
        for (int a = 0; a < p->n_actions; a++) {
            _FSPAction *ac = &p->actions[a];
            double dy_eff = (cur.foot == 0) ? ac->dy : -ac->dy;
            double ndx_world = cs * ac->dx - sn * dy_eff;
            double ndy_world = sn * ac->dx + cs * dy_eff;
            double nx = cur.x + ndx_world;
            double ny = cur.y + ndy_world;
            double nt = cur.theta + ((cur.foot == 0) ? ac->dtheta : -ac->dtheta);
            int nfoot = 1 - cur.foot;
            // Validity check via callback.
            if (!is_valid(_f2i(nx), _f2i(ny), _f2i(nt))) continue;

            double step_len = sqrt(ndx_world*ndx_world + ndy_world*ndy_world);
            double new_g = cur.g + ac->cost + step_len;

            long long key = _state_key(p, nx, ny, nt, nfoot);
            double existing_g = 0;
            int existing_idx = -1;
            int seen = _hash_get(table, cap, key, &existing_g, &existing_idx);
            if (seen && existing_g <= new_g) continue;

            // Push new node.
            if (p->n_nodes >= p->cap_nodes) {
                p->cap_nodes *= 2;
                p->nodes = (_FSPNode *)realloc(p->nodes, p->cap_nodes * sizeof(_FSPNode));
            }
            int new_idx = p->n_nodes++;
            _FSPNode *nn = &p->nodes[new_idx];
            nn->x = nx; nn->y = ny; nn->theta = nt; nn->foot = nfoot;
            nn->g = new_g; nn->parent = u;

            _hash_put(table, cap, key, new_g, new_idx);

            // Heuristic.
            double dxh = xg - nx, dyh = yg - ny;
            double hh = sqrt(dxh*dxh + dyh*dyh) / max_step;
            if (heap_size + 1 >= heap_cap) {
                heap_cap = heap_cap * 2 + 16;
                heap = (_FSPHeapItem *)realloc(heap, heap_cap * sizeof(_FSPHeapItem));
            }
            _heap_push(heap, &heap_size, new_g + hh, new_idx);
        }
    }

    if (found) {
        // Reconstruct path.
        int cnt = 0;
        for (int v = goal_idx; v != -1; v = p->nodes[v].parent) cnt++;
        p->path_len = cnt;
        p->path = (int *)malloc(cnt * sizeof(int));
        int j = cnt - 1;
        for (int v = goal_idx; v != -1; v = p->nodes[v].parent) p->path[j--] = v;
    }

    free(table);
    free(heap);
    return found ? (long long)p->path_len : 0;
}

long long nuc_fsp_path_len(long long h) {
    NFSP *p = (NFSP *)(void *)(size_t)h;
    if (!p) return 0;
    return (long long)p->path_len;
}

long long nuc_fsp_path_x(long long h, long long i) {
    NFSP *p = (NFSP *)(void *)(size_t)h;
    if (!p || i < 0 || i >= (long long)p->path_len) return _f2i(0.0);
    return _f2i(p->nodes[p->path[i]].x);
}
long long nuc_fsp_path_y(long long h, long long i) {
    NFSP *p = (NFSP *)(void *)(size_t)h;
    if (!p || i < 0 || i >= (long long)p->path_len) return _f2i(0.0);
    return _f2i(p->nodes[p->path[i]].y);
}
long long nuc_fsp_path_theta(long long h, long long i) {
    NFSP *p = (NFSP *)(void *)(size_t)h;
    if (!p || i < 0 || i >= (long long)p->path_len) return _f2i(0.0);
    return _f2i(p->nodes[p->path[i]].theta);
}
long long nuc_fsp_path_foot(long long h, long long i) {
    NFSP *p = (NFSP *)(void *)(size_t)h;
    if (!p || i < 0 || i >= (long long)p->path_len) return -1;
    return (long long)p->nodes[p->path[i]].foot;
}
long long nuc_fsp_path_cost(long long h) {
    NFSP *p = (NFSP *)(void *)(size_t)h;
    if (!p || p->path_len == 0) return _f2i(0.0);
    int last = p->path[p->path_len - 1];
    return _f2i(p->nodes[last].g);
}

void nuc_fsp_free(long long h) {
    NFSP *p = (NFSP *)(void *)(size_t)h;
    if (!p) return;
    if (p->actions) free(p->actions);
    if (p->nodes) free(p->nodes);
    if (p->path) free(p->path);
    free(p);
}
