#!/usr/bin/env python3
"""
gen_rod_manifest.py — Generate docs/rfcs/rod_manifest.toml from
stdlib/rods/*.nr.

Parallel artifact to docs/rfcs/helper_manifest.toml. Where the helper
manifest catalogs the 676 compiler-emitted __nucleor_* symbols (the ABI
surface), the rod manifest catalogs the 121 user-facing modules — what
appears in `import "stdlib/rods/<name>.nr"` calls.

Per-row fields:
  name             - bare rod name (e.g. "math")
  path             - relative path
  description      - first non-blank descriptive line from the file's
                     leading comment block (or "" if absent)
  function_count   - number of `fn` definitions (top-level)
  imports          - rod names the file imports from `stdlib/rods/`
  cfile_count      - number of `#cfile` runtime files referenced
  loc              - source lines (excluding blanks/comments)

Usage: python tools/gen_rod_manifest.py
Output: docs/rfcs/rod_manifest.toml (overwrites)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RODS = ROOT / "stdlib" / "rods"
OUT = ROOT / "docs" / "rfcs" / "rod_manifest.toml"


def parse_rod(path):
    text = path.read_text(encoding="utf-8", errors="replace")
    name = path.stem

    # Extract leading comment block — first run of '//'-prefixed lines
    lines = text.splitlines()
    header_lines = []
    for line in lines:
        s = line.strip()
        if s.startswith("//"):
            # Strip leading "//" and any "===" decoration
            content = s[2:].strip()
            if content and not set(content) <= set("="):
                header_lines.append(content)
        elif s == "":
            if header_lines:
                continue  # skip blank lines inside header
            else:
                continue
        else:
            break

    # Description = first informative header line (skip "rods/X" titles + meta lines)
    description = ""
    for h in header_lines:
        low = h.lower()
        if low.startswith("rods/"):
            # "rods/math — Integer math utilities" → take after the —
            for sep in (" — ", " - ", ": "):
                if sep in h:
                    description = h.split(sep, 1)[1].strip()
                    break
            if description:
                break
        if low.startswith(("import:", "depends:", "provides:", "see ", "#cfile")):
            continue
        description = h
        break

    # Count fn definitions (top-level only — match start of line)
    fn_count = len(re.findall(r'^\s*(?:pub\s+)?fn\s+\w+', text, re.MULTILINE))

    # Count #cfile directives
    cfile_count = len(re.findall(r'^\s*#cfile\b', text, re.MULTILINE))

    # Parse imports
    imports = sorted(set(re.findall(r'import\s+"stdlib/rods/([a-zA-Z0-9_]+)\.nr"', text)))

    # LOC: non-blank, non-pure-comment lines
    loc = 0
    for line in lines:
        s = line.strip()
        if not s:
            continue
        if s.startswith("//"):
            continue
        loc += 1

    return {
        "name": name,
        "path": str(path.relative_to(ROOT)).replace("\\", "/"),
        "description": description,
        "function_count": fn_count,
        "imports": imports,
        "cfile_count": cfile_count,
        "loc": loc,
    }


def main():
    rod_files = sorted(RODS.glob("*.nr"))
    rows = [parse_rod(p) for p in rod_files]
    rows.sort(key=lambda r: r["name"])

    out_lines = []
    out_lines.append("# rod_manifest.toml")
    out_lines.append("#")
    out_lines.append("# Source-of-truth catalog for every user-facing rod in")
    out_lines.append("# stdlib/rods/. Generated by tools/gen_rod_manifest.py from")
    out_lines.append("# the .nr files themselves. Do not edit by hand — re-run the")
    out_lines.append("# generator after adding any rod.")
    out_lines.append("#")
    out_lines.append("# Schema: see docs/rfcs/rod_manifest_schema.md")
    out_lines.append("# Companion: docs/rfcs/helper_manifest.toml (ABI surface)")
    out_lines.append(f"# Total rods: {len(rows)}")
    out_lines.append(f"# Total fn definitions: {sum(r['function_count'] for r in rows)}")
    out_lines.append(f"# Total LOC: {sum(r['loc'] for r in rows)}")
    out_lines.append("")

    # Sanity: rods with no description (worth flagging for human review)
    no_desc = [r for r in rows if not r["description"]]
    if no_desc:
        out_lines.append("# ============================================================")
        out_lines.append("# REVIEW REQUIRED — rods with no extractable description")
        out_lines.append("# ============================================================")
        out_lines.append("# Add a leading '// rods/<name> — <description>' line to fix.")
        for r in no_desc:
            out_lines.append(f"#   {r['name']}")
        out_lines.append("")

    for r in rows:
        out_lines.append("[[rod]]")
        out_lines.append(f'name           = "{r["name"]}"')
        out_lines.append(f'path           = "{r["path"]}"')
        # Escape backslash + quote in description
        desc_esc = r["description"].replace("\\", "\\\\").replace('"', '\\"')
        out_lines.append(f'description    = "{desc_esc}"')
        out_lines.append(f'function_count = {r["function_count"]}')
        out_lines.append(f'cfile_count    = {r["cfile_count"]}')
        out_lines.append(f'loc            = {r["loc"]}')
        if r["imports"]:
            quoted = ", ".join(f'"{x}"' for x in r["imports"])
            out_lines.append(f'imports        = [{quoted}]')
        else:
            out_lines.append('imports        = []')
        out_lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out_lines), encoding="utf-8")

    print(f"Wrote {OUT}")
    print(f"Total rods: {len(rows)}")
    print(f"Total fn: {sum(r['function_count'] for r in rows)}")
    print(f"Total LOC: {sum(r['loc'] for r in rows)}")
    print(f"Without description: {len(no_desc)}")


if __name__ == "__main__":
    main()
