#!/usr/bin/env python3
"""
gen_helper_manifest.py — Generate docs/rfcs/helper_manifest.toml from the
canonical compiler ABI tables and runtime C source.

Authoritative sources (read-only):
  compiler/nucleor_s1_compiler.nr   (get_rt_name / is_ptr_ret / is_ptr_arg /
                                     is_void_ret tables + IR `declare` block)
  compiler/nucleor_tools_suite.nr   (mirror — drift gate enforces parity)
  stdlib/runtime/*.c                (__nucleor_* definitions)

Usage: python tools/gen_helper_manifest.py

Output: docs/rfcs/helper_manifest.toml (overwrites)

This script is the executable form of the Helpers.md contract Phase 2:
- Inventories every helper symbol declared by the compiler.
- Classifies by name pattern into the 13 v0.2.41 taxonomy classes
  (PureMath, VectorOps, PanickingArith, StringFormat, IO, Collection,
  TensorOps, Concurrency, Time, DataCodec, Random, ToolingMeta,
  Allocation; the original v0.2.39 walk proposed 14 but the
  Unclassified bucket collapsed to zero by v0.2.41).
- Marks unclassified entries as `class = "Unclassified"` and lists
  them under the file's REVIEW REQUIRED block (zero rows since v0.2.41).
- Marks declared-but-undefined entries as `stability = "experimental"`
  with a `notes` flag (latent linker gaps from earlier eras).
- Populates policy-sensitive fields (effects, taint, units,
  proof_obligation) via the resolution chain
  NAME_OVERRIDES → PATTERN_OVERRIDES → CLASS_DEFAULTS → "TODO"
  (added v0.2.74; populated 95.1% of the 676 helpers as of v0.2.78).

Re-run this script after adding any new helper. The Helpers.md contract
going-forward constraint requires the manifest to stay in sync.
"""

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
S1 = ROOT / "compiler" / "nucleor_s1_compiler.nr"
RT_DIR = ROOT / "stdlib" / "runtime"
OUT = ROOT / "docs" / "rfcs" / "helper_manifest.toml"


# ---------- Pull ABI tables from the s1 compiler source ----------

def parse_get_rt_name(src):
    """Return list of (name, symbol) pairs from the get_rt_name table."""
    out = []
    rx = re.compile(r'if str_eq\(name, "([^"]+)"\) \{ return "([^"]+)";')
    for m in rx.finditer(src):
        name, symbol = m.group(1), m.group(2)
        if symbol.startswith("__nucleor_"):
            out.append((name, symbol))
    return out


def parse_is_void_ret(src):
    """Return set of names declared void-returning."""
    # Match the is_void_ret function body by finding the fn definition
    fn_match = re.search(r'fn is_void_ret\(name: str\)[^{]*\{(.*?)\n\}',
                         src, re.DOTALL)
    if not fn_match:
        return set()
    body = fn_match.group(1)
    return set(re.findall(r'if str_eq\(name, "([^"]+)"\) \{ return 1;', body))


def parse_is_ptr_ret(src):
    """Return set of names declared ptr-returning."""
    fn_match = re.search(r'fn is_ptr_ret\(name: str\)[^{]*\{(.*?)\nfn ',
                         src, re.DOTALL)
    if not fn_match:
        return set()
    body = fn_match.group(1)
    return set(re.findall(r'if str_eq\(name, "([^"]+)"\) \{ return 1;', body))


def parse_ir_declares(src):
    """Return dict symbol -> (ret_type, arg_types) from IR declares."""
    out = {}
    rx = re.compile(
        r'sb_append\(sb, "declare ([a-z0-9]+) @(__nucleor_[a-zA-Z0-9_]+)\(([^)]*)\)\\n"'
    )
    for m in rx.finditer(src):
        ret, sym, args = m.group(1), m.group(2), m.group(3).strip()
        arg_list = [a.strip() for a in args.split(",")] if args else []
        out[sym] = (ret, arg_list)
    return out


def collect_runtime_defs():
    """Set of __nucleor_* symbols defined in stdlib/runtime/*.c.

    Includes symbols generated by NUC_DEFINE_SIGNED_OVERFLOW /
    NUC_DEFINE_UNSIGNED_OVERFLOW macros — for each instantiation
    we expand to the 9 functions the macro defines.
    """
    out = set()

    # The narrow-width arith macros expand to exactly these 9 helpers per width:
    NARROW_ARITH = [
        "wrapping_add", "wrapping_sub", "wrapping_mul",
        "saturating_add", "saturating_sub", "saturating_mul",
        "checked_add", "checked_sub", "checked_mul",
    ]

    for c in sorted(RT_DIR.glob("*.c")):
        text = c.read_text(encoding="utf-8", errors="replace")

        # Direct function definitions
        for m in re.finditer(r'\b(__nucleor_[a-zA-Z0-9_]+)\s*\(', text):
            out.add(m.group(1))

        # NUC_DEFINE_SIGNED_OVERFLOW(width, ...)  → 9 helpers per width
        for m in re.finditer(r'NUC_DEFINE_(?:SIGNED|UNSIGNED)_OVERFLOW\s*\(\s*([a-zA-Z0-9_]+)\s*,', text):
            width = m.group(1)
            for fn in NARROW_ARITH:
                out.add(f"__nucleor_{fn}_{width}")

    return out


# ---------- Classification ----------

CLASS_RULES = [
    # (class_name, list of regex patterns matched against bare helper name)
    ("VectorOps",       [r"^vec_(?!u8|deque)", r"^vec_u8_", r"^f32x4_", r"^i32x4_",
                         r"^simd_", r"^vector_"]),
    ("Collection",      [r"^hashmap_", r"^hashset_", r"^btreemap_", r"^btreeset_",
                         r"^heapmap_", r"^vecdeque_"]),
    ("StringFormat",    [r"^str_", r"^string_", r"^sb_", r"^format_", r"^format[0-9]",
                         r"^chr$", r"^char_", r"^int_to_(str|hex|bin|oct)$",
                         r"^f64_to_str$", r"^bool_to_str$",
                         r"^str_to_(i64|f64|bool)$", r"^str_to_i64_radix$",
                         r"^parse_(hex|bin)$"]),
    ("IO",              [r"^fs_", r"^path_", r"^file_", r"^env_", r"^getenv$",
                         r"^getcwd$", r"^process_id$", r"^os_", r"^read_(line|int|i64|byte)$",
                         r"^stdin_", r"^stdout_", r"^stderr_", r"^isatty_",
                         r"^print", r"^eprint", r"^pipe_", r"^proc_", r"^system$",
                         r"^socket_", r"^http_", r"^tcp_", r"^udp_", r"^putchar$",
                         r"^args_", r"^init_args$", r"^dbg_"]),
    ("Concurrency",     [r"^mutex_", r"^channel_", r"^chan_", r"^thread_",
                         r"^rwlock_", r"^cancel_token_", r"^once_", r"^atomic_",
                         r"^cas_", r"^par_", r"^scheduler_", r"^ambient_scheduler",
                         r"^cpu_count$"]),
    ("Random",          [r"^rng_", r"^random_", r"^ambient_random$"]),
    ("Time",            [r"^time_", r"^sleep_", r"^now_"]),
    ("PanickingArith",  [r"^checked_", r"^saturating_", r"^wrapping_",
                         r"^overflow", r"^panic", r"^trap_", r"^bounds_check",
                         r"^stack_probe", r"^assert$", r"^sat_i32$", r"^wrap_i32$"]),
    ("PureMath",        [r"^popcount$", r"^leading_zeros$", r"^trailing_zeros$",
                         r"^byte_swap$", r"^rotate_left$", r"^rotate_right$",
                         r"^count_ones$", r"^count_zeros$",
                         r"^i64_", r"^f64_", r"^f32_", r"^i32_", r"^f16_",
                         r"^f8e[45]m[23]_to_f32$",
                         r"^abs$", r"^min$", r"^max$", r"^clamp$", r"^sqrt$",
                         r"^sin$", r"^cos$", r"^tan$", r"^pow$", r"^exp$",
                         r"^log$", r"^floor$", r"^ceil$", r"^round$",
                         r"^fabs$", r"^fmod$", r"^sigmoid$", r"^tanh$",
                         r"^relu$", r"^gelu$",
                         r"^as_(f32|f64|i8|i16|i32|i64|u8|u16|u32|u64)$",
                         r"^buf_(read|write)_u(8|16|32|64)"]),
    ("DataCodec",       [r"^toml_", r"^json_", r"^csv_", r"^ini_", r"^base64_",
                         r"^msgpack_", r"^uuid_", r"^sha256", r"^fnv1a",
                         r"^murmur3", r"^crc32", r"^bit_"]),
    ("Allocation",      [r"^region_", r"^arena_", r"^alloc_", r"^free$",
                         r"^realloc$", r"^drop_", r"^malloc$", r"^memcpy$",
                         r"^calloc$", r"^capture_"]),
    ("TensorOps",       [r"^tensor_", r"^matmul", r"^conv2d", r"^attention",
                         r"^cuda_", r"^gpu_", r"^device_", r"^layout_",
                         r"^dlpack_", r"^kvcache_", r"^kvprefix_"]),
    ("ToolingMeta",     [r"^plot_", r"^profile_", r"^certify_", r"^evidence_",
                         r"^impact_", r"^audit_", r"^policy_", r"^doc_",
                         r"^manifest_", r"^stage_", r"^bench_", r"^cli_",
                         r"^test_", r"^summary_", r"^py_eval$",
                         r"^rods_f64_", r"^assert_(eq|ne)$", r"^dbg$"]),
    # bf16 reduced-precision falls in PureMath (similar to f16_*)
    ("PureMath",        [r"^bf16_"]),
]


# Per-helper `since` release. Values not listed default to "0.1.0" (the
# v0.1 baseline). The v0.2.x stdlib enrichment chain (v0.2.18..v0.2.30
# plus a few earlier rolling additions) is enumerated here. Keep in sync
# with the CHANGELOG.md per-release helper lists.
SINCE_MAP = {
    # v0.2.9: Vec functional helpers (RFC-0024 phase 1)
    "vec_map_i64": "0.2.9", "vec_filter_i64": "0.2.9",
    "vec_fold_i64": "0.2.9", "vec_each_i64": "0.2.9",
    "vec_sum_i64": "0.2.9", "vec_min_i64": "0.2.9", "vec_max_i64": "0.2.9",
    # v0.2.10: Vec reductions
    "vec_contains_i64": "0.2.10", "vec_index_of_i64": "0.2.10",
    "vec_reverse_i64": "0.2.10", "vec_sort_i64": "0.2.10",
    "vec_clone_i64": "0.2.10", "vec_clear_i64": "0.2.10",
    # v0.2.13: Vec arithmetic + format extensions
    "vec_avg_i64": "0.2.13", "vec_dot_i64": "0.2.13",
    "vec_count_eq_i64": "0.2.13", "vec_any_i64": "0.2.13",
    "vec_all_i64": "0.2.13",
    "vec_sum_f64": "0.2.13", "vec_min_f64": "0.2.13", "vec_max_f64": "0.2.13",
    # v0.2.14: char predicates
    "char_is_alpha": "0.2.14", "char_is_digit": "0.2.14",
    "char_is_alnum": "0.2.14", "char_is_whitespace": "0.2.14",
    "char_is_upper": "0.2.14", "char_is_lower": "0.2.14",
    "char_is_hex_digit": "0.2.14", "char_is_ascii": "0.2.14",
    "char_is_punct": "0.2.14",
    "char_to_upper": "0.2.14", "char_to_lower": "0.2.14",
    "char_digit_value": "0.2.14",
    # v0.2.15: RNG bridges
    "rng_int": "0.2.15", "rng_uniform": "0.2.15", "rng_normal": "0.2.15",
    "rng_bernoulli": "0.2.15", "rng_exponential": "0.2.15",
    "rng_seed": "0.2.15", "random_uniform": "0.2.15", "random_normal": "0.2.15",
    # v0.2.16: HashMap iteration + ISO time
    "hashmap_keys": "0.2.16", "hashmap_values": "0.2.16",
    "time_iso_now": "0.2.16", "time_format_iso": "0.2.16",
    # v0.2.17: hash helpers + raw print
    "fnv1a_64_str": "0.2.17", "fnv1a_64_i64": "0.2.17", "murmur3_64": "0.2.17",
    "print_raw": "0.2.17", "eprint_raw": "0.2.17",
    # v0.2.18: f64 magnitude/sign + bit population
    "f64_abs": "0.2.18", "f64_min": "0.2.18", "f64_max": "0.2.18",
    "f64_sign": "0.2.18", "f64_copy_sign": "0.2.18",
    "count_ones": "0.2.18", "count_zeros": "0.2.18",
    # v0.2.19: filesystem extras
    "fs_temp_dir": "0.2.19", "fs_current_dir": "0.2.19",
    "fs_remove_dir": "0.2.19", "fs_copy_file": "0.2.19",
    "fs_canonicalize": "0.2.19",
    # v0.2.20: env extras + string round-out
    "env_has": "0.2.20", "env_keys": "0.2.20",
    "str_is_empty": "0.2.20", "str_count": "0.2.20",
    "str_reverse": "0.2.20", "str_trim_start": "0.2.20", "str_trim_end": "0.2.20",
    # v0.2.21: time decomposition
    "time_year": "0.2.21", "time_month": "0.2.21", "time_day": "0.2.21",
    "time_hour": "0.2.21", "time_minute": "0.2.21", "time_second": "0.2.21",
    "time_weekday": "0.2.21", "time_day_of_year": "0.2.21",
    "time_elapsed_ms": "0.2.21",
    # v0.2.22: vec mutation + accessor
    "vec_first": "0.2.22", "vec_last": "0.2.22", "vec_is_empty": "0.2.22",
    "vec_swap": "0.2.22", "vec_extend": "0.2.22",
    "vec_remove_at": "0.2.22", "vec_insert_at": "0.2.22",
    # v0.2.23: path utilities
    "path_separator": "0.2.23", "path_is_absolute": "0.2.23",
    "path_normalize": "0.2.23", "path_with_extension": "0.2.23",
    "path_strip_extension": "0.2.23", "path_components": "0.2.23",
    # v0.2.24: parse + stringify
    "str_to_i64": "0.2.24", "str_to_f64": "0.2.24", "str_to_bool": "0.2.24",
    "int_to_str": "0.2.24", "f64_to_str": "0.2.24", "bool_to_str": "0.2.24",
    # v0.2.25: base conversion
    "int_to_hex": "0.2.25", "int_to_bin": "0.2.25", "int_to_oct": "0.2.25",
    "str_to_i64_radix": "0.2.25", "parse_hex": "0.2.25", "parse_bin": "0.2.25",
    # v0.2.26: string padding + join + explode
    "str_pad_left": "0.2.26", "str_pad_right": "0.2.26", "str_center": "0.2.26",
    "str_join": "0.2.26", "str_lines": "0.2.26", "str_chars": "0.2.26",
    # v0.2.27: HashMap accessor + bulk
    "hashmap_is_empty": "0.2.27", "hashmap_get_or": "0.2.27",
    "hashmap_merge": "0.2.27", "hashmap_clone": "0.2.27",
    # v0.2.28: checked div/rem/neg
    "checked_div": "0.2.28", "checked_rem": "0.2.28", "checked_neg": "0.2.28",
    "wrapping_div": "0.2.28", "wrapping_rem": "0.2.28", "wrapping_neg": "0.2.28",
    "saturating_neg": "0.2.28",
    # v0.2.29: random + shuffle/sample
    "random_int": "0.2.29", "random_bool": "0.2.29", "random_choice": "0.2.29",
    "vec_shuffle": "0.2.29", "vec_sample": "0.2.29", "random_fill": "0.2.29",
    # v0.2.30: Vec statistics
    "vec_mean_f64": "0.2.30", "vec_median_f64": "0.2.30",
    "vec_variance_f64": "0.2.30", "vec_stddev_f64": "0.2.30",
    "vec_range_i64": "0.2.30", "vec_percentile_f64": "0.2.30",
}


# Helpers known to be intentional v0.4 placeholders / forward-declarations.
# These are declared in IR so the parser knows the names but lack runtime
# definitions — they're the deferred items from v0.4.0 milestone tracker.
INTENTIONAL_PLACEHOLDER = {
    # RFC-0001/0002 — region / arena allocators, target v0.4
    "__nucleor_arena_alloc", "__nucleor_arena_destroy", "__nucleor_arena_new",
    "__nucleor_arena_reset",
    "__nucleor_region_alloc", "__nucleor_region_free", "__nucleor_region_new",
    "__nucleor_region_reset",
    "__nucleor_capture_get", "__nucleor_capture_set",
    # RFC-0007 phase 2 — cancel tokens, scheduler, par_*, rwlock — v0.4
    "__nucleor_ambient_scheduler",
    "__nucleor_cancel_token_cancel", "__nucleor_cancel_token_is_cancelled",
    "__nucleor_cancel_token_new",
    "__nucleor_par_fold", "__nucleor_par_map", "__nucleor_par_reduce",
    "__nucleor_rwlock_new", "__nucleor_rwlock_read", "__nucleor_rwlock_unlock",
    "__nucleor_rwlock_write",
    # RFC-0024 phase 2 — Iterator trait + adapter chain, target v0.4
    "__nucleor_vec_iter", "__nucleor_vec_map", "__nucleor_vec_filter",
    "__nucleor_vec_fold", "__nucleor_vec_all", "__nucleor_vec_any",
    "__nucleor_vec_count", "__nucleor_vec_chain", "__nucleor_vec_skip",
    "__nucleor_vec_take", "__nucleor_vec_sum",
    # GPU / device / LLM domain — target v0.4+
    "__nucleor_ambient_random",
    "__nucleor_device_alloc", "__nucleor_device_free",
    "__nucleor_device_transfer",
    "__nucleor_kvcache_append", "__nucleor_kvcache_compact",
    "__nucleor_kvcache_evict", "__nucleor_kvcache_free", "__nucleor_kvcache_new",
    "__nucleor_kvcache_read_prefix", "__nucleor_kvprefix_free",
    "__nucleor_tensor_center", "__nucleor_tensor_clip", "__nucleor_tensor_entropy",
    "__nucleor_tensor_greedy", "__nucleor_tensor_l1", "__nucleor_tensor_l2",
    "__nucleor_tensor_len", "__nucleor_tensor_mad", "__nucleor_tensor_median",
    "__nucleor_tensor_minmax", "__nucleor_tensor_normalize_l2",
    "__nucleor_tensor_percentile", "__nucleor_tensor_sample_eps",
    "__nucleor_tensor_sample_gumbel", "__nucleor_tensor_sample_nucleus_temp",
    "__nucleor_tensor_sample_rank", "__nucleor_tensor_sample_topk_temp",
    "__nucleor_tensor_top2_gap", "__nucleor_tensor_view", "__nucleor_tensor_zscore",
    "__nucleor_simd_add", "__nucleor_simd_fma", "__nucleor_simd_mul",
    "__nucleor_vector_add", "__nucleor_vector_broadcast", "__nucleor_vector_fma",
    "__nucleor_vector_mul", "__nucleor_vector_new", "__nucleor_vector_reduce_sum",
    # Tooling / profile — partial; full implementation deferred
    "__nucleor_profile_end", "__nucleor_profile_start",
    # Legacy — pre-v0.2 codepaths kept for ABI compat
    "__nucleor_py_eval",
    "__nucleor_rods_f64_add", "__nucleor_rods_f64_div",
    "__nucleor_rods_f64_encode", "__nucleor_rods_f64_sub",
    # Standalone narrow-width sentinels (not part of the macro family)
    "__nucleor_sat_i32", "__nucleor_wrap_i32",
    # Stdlib bridge synonyms (calls existing definitions under a different name)
    "__nucleor_sha256",  # redirects to __nucleor_sha256_hex
    "__nucleor_putchar", # libc symbol, not __nucleor_*
}


def classify(name):
    for cls, patterns in CLASS_RULES:
        for p in patterns:
            if re.match(p, name):
                return cls
    return "Unclassified"


# Per-helper-name override. Takes precedence over PATTERN_OVERRIDES and
# CLASS_DEFAULTS. Use this for individual helpers whose semantics
# diverge from their class default (e.g. PanickingArith's `panic` and
# `assert` actually panic, while the bulk of the class — checked_/
# wrapping_/saturating_ — return tagged results).
#
# Each value is (effects_list, taint, proof_obligation).
NAME_OVERRIDES = {
    # PanickingArith — actually-panicking members (the bulk of the
    # class is non-panicking and lives under PATTERN_OVERRIDES).
    "panic":            (["panic"], "passthrough", "callsite_unreachable_or_recoverable"),
    "assert":           (["panic"], "passthrough", "predicate_holds"),
    # ToolingMeta — assertion macros panic on failure.
    "assert_eq":        (["panic"], "passthrough", "predicate_holds"),
    "assert_ne":        (["panic"], "passthrough", "predicate_holds"),
    # ToolingMeta — debug print to stderr.
    "dbg":              (["io"],    "passthrough", "io_capability_required"),
    # ToolingMeta — manifest validation builds a small report string.
    "manifest_report":  (["alloc"], "passthrough", "none"),
    "manifest_validate":(["alloc"], "passthrough", "none"),
    # DataCodec — pure hash helpers (return a u64; no allocation).
    "crc32":            ([],        "passthrough", "none"),
    "crc32_update":     ([],        "passthrough", "none"),
    "fnv1a_64_i64":     ([],        "passthrough", "none"),
    "fnv1a_64_str":     ([],        "passthrough", "none"),
    "murmur3_64":       ([],        "passthrough", "none"),
    # StringFormat — string_print actually does I/O (despite living
    # in StringFormat by name pattern).
    "string_print":     (["io"],    "passthrough", "io_capability_required"),
    # ToolingMeta — legacy rods bridge. Pure f64 arithmetic (kept
    # for pre-v0.2 ABI compat). Behavior matches standard f64 —
    # division by zero returns NaN/inf, no panic.
    "rods_f64_add":     ([],        "passthrough", "none"),
    "rods_f64_sub":     ([],        "passthrough", "none"),
    "rods_f64_div":     ([],        "passthrough", "none"),
    "rods_f64_encode":  (["alloc"], "passthrough", "none"),
}


# Per-name-regex override. Same precedence as NAME_OVERRIDES (matched
# only if the helper's name didn't hit NAME_OVERRIDES). Matched in
# order; first hit wins. Use this for whole helper families that share
# semantics (e.g. all `checked_*` are pure, regardless of width).
#
# Each entry is (compiled_regex, (effects_list, taint, proof_obligation)).
PATTERN_OVERRIDES = [
    # PanickingArith's non-panicking family — checked_*/wrapping_*/
    # saturating_* return Option/wrap/saturate instead of panicking,
    # and never allocate. Effectively pure.
    (re.compile(r"^(checked|wrapping|saturating)_"),
     ([], "passthrough", "none")),
    # Standalone narrow-width sentinels — saturating/wrapping i32 casts.
    (re.compile(r"^(sat|wrap)_i32$"),
     ([], "passthrough", "none")),
    # StringFormat: pure character predicates and conversions.
    (re.compile(r"^char_"),
     ([], "passthrough", "none")),
    # StringFormat: int -> char.
    (re.compile(r"^chr$"),
     ([], "passthrough", "none")),
    # StringFormat: pure str/string predicates and accessors that
    # return a scalar (bool / i64 / i32) without allocating.
    (re.compile(r"^str_(eq|contains|count|ends_with|starts_with|index_of|is_empty|len|char_at)$"),
     ([], "passthrough", "none")),
    (re.compile(r"^str_to_(i64|f64|bool|i64_radix)$"),
     ([], "passthrough", "none")),
    (re.compile(r"^parse_(hex|bin)$"),
     ([], "passthrough", "none")),
    (re.compile(r"^string_(capacity|eq|eq_str|get_byte|len|starts_with|ends_with|contains|as_ptr)$"),
     ([], "passthrough", "none")),
    # Collection: pure read-only accessors across hashmap/hashset/
    # btreemap/btreeset/vecdeque. Allocation-free (return Option /
    # bool / i64 / i32 / scalar).
    (re.compile(r"^(hashmap|hashset|btreemap|btreeset|vecdeque)_(get|contains|len|capacity|is_empty|get_or|key_at|val_at|at)$"),
     ([], "passthrough", "none")),
    # IO class — pure compile-time-constant queries.
    (re.compile(r"^os_(family|pointer_width)$"),
     ([], "passthrough", "none")),
    # IO class — pure path predicates (return bool / static str).
    (re.compile(r"^path_(is_absolute|separator)$"),
     ([], "passthrough", "none")),
    # IO class — string-transforming path / fs helpers. Allocate the
    # output string but do NOT touch the filesystem.
    (re.compile(r"^path_(components|normalize|strip_extension|with_extension)$"),
     (["alloc"], "passthrough", "none")),
    (re.compile(r"^fs_(basename|dirname|extension|join)$"),
     (["alloc"], "passthrough", "none")),
    # IO class — stdin reads. Introduce external taint into the
    # value graph (output taint = input taint ∪ external source).
    (re.compile(r"^read_(byte|i64|line)$"),
     (["io"], "propagates", "io_capability_required")),
    # IO class — env / fs / process-state reads. Same taint behavior
    # as stdin reads — they pull external state into the program.
    (re.compile(r"^env_(get|has|keys)$"),
     (["io"], "propagates", "io_capability_required")),
    (re.compile(r"^getenv$"),
     (["io"], "propagates", "io_capability_required")),
    (re.compile(r"^getcwd$"),
     (["io"], "propagates", "io_capability_required")),
    (re.compile(r"^process_id$"),
     (["io"], "propagates", "io_capability_required")),
    (re.compile(r"^isatty_"),
     (["io"], "propagates", "io_capability_required")),
    (re.compile(r"^args_(count|get)$|^init_args$"),
     (["io"], "propagates", "io_capability_required")),
    (re.compile(r"^fs_(exists|is_dir|is_file|size|mtime|list_dir|canonicalize|current_dir|temp_dir)$"),
     (["io"], "propagates", "io_capability_required")),
    (re.compile(r"^file_read_"),
     (["io"], "propagates", "io_capability_required")),
    # IO class — system() execs a subprocess; subprocess can write to
    # stdout / stderr / files which would propagate taint upstream.
    (re.compile(r"^system$"),
     (["io"], "propagates", "io_capability_required")),
    # DataCodec — toml_get_*/has are pure reads from a parsed TOML
    # handle (the parse already happened; lookup is in-memory).
    (re.compile(r"^toml_(get_int|get_str|has)$"),
     ([], "passthrough", "none")),
    # DataCodec — toml_parse_file does both I/O and parsing.
    (re.compile(r"^toml_parse_file$"),
     (["io"], "propagates", "io_capability_required")),
    # DataCodec — uuid_v4 generates a fresh UUID via the RNG.
    (re.compile(r"^uuid_v4$"),
     (["random", "alloc"], "passthrough", "rng_capability_required")),
    # TensorOps — pure read-only accessors / reductions. Return a
    # scalar (i64 / f64 bit pattern) without allocating.
    (re.compile(r"^tensor_(get|cols|rows|max|min|mean|sum|stddev|variance)$"),
     ([], "passthrough", "bounds_within_shape")),
    # TensorOps — in-place mutations. No allocation; modify the
    # pointed-to tensor.
    (re.compile(r"^tensor_(set|fill)$"),
     ([], "passthrough", "bounds_within_shape")),
    # TensorOps — allocate a fresh tensor as output. CPU-bound
    # implementations as of v0.2; GPU paths (matmul on cuda etc.)
    # will land alongside the v0.4 device-effect formalization.
    (re.compile(r"^tensor_(zeros|ones|transpose|matmul)$"),
     (["alloc"], "passthrough", "shape_compatible")),
]


# Per-class default population for the policy-sensitive fields. Classes
# with uniform per-helper semantics live here; classes with per-helper
# divergence (StringFormat, IO, Collection, TensorOps, DataCodec,
# ToolingMeta) stay under the TODO sentinel for the rows that don't
# match a NAME_OVERRIDES / PATTERN_OVERRIDES entry, until per-name
# tables are populated in follow-on releases.
#
# Schema: each value is (effects_list, taint, proof_obligation). The
# generator emits effects as a TOML array literal, taint and
# proof_obligation as quoted strings.
CLASS_DEFAULTS = {
    # Effect-free, deterministic — no panic, no heap, no syscall.
    "PureMath":       ([],            "passthrough", "none"),
    # VectorOps allocate a result Vec but otherwise carry input
    # taint through verbatim. Bounds are checked at call site.
    "VectorOps":      (["alloc"],     "passthrough", "bounds_within_len"),
    # RNG bridges. Require RNG capability (seeded explicitly or
    # ambient-random capability granted). Output is non-deterministic
    # but doesn't taint downstream values.
    "Random":         (["random"],    "passthrough", "rng_capability_required"),
    # Wall-clock and monotonic clock reads. Capability-gated by the
    # ambient clock effect (matches schema vocabulary "clock").
    "Time":           (["clock"],     "passthrough", "clock_capability_required"),
    # Mutex/channel/atomic/thread/par primitives. Require sync effect.
    # Memory-ordering guarantee handed to the caller as proof obligation.
    "Concurrency":    (["sync"],      "passthrough", "happens_before_release_acquire"),
    # arena_*/region_*/alloc_*/free_*/realloc_*/capture_*. Require
    # alloc effect. Caller must own the arena/region or hold the
    # allocator capability.
    "Allocation":     (["alloc"],     "passthrough", "alloc_capability_or_arena_owned"),
    # StringFormat — string-builder / int-to-string / format helpers
    # all allocate the output buffer. Pure read-only members are
    # singled out by PATTERN_OVERRIDES above.
    "StringFormat":   (["alloc"],     "passthrough", "none"),
    # Collection — mutators (insert / remove / push / pop / clone /
    # merge / new / with_capacity / clear / free / keys / values)
    # touch the allocator. Pure access methods are singled out by
    # PATTERN_OVERRIDES above.
    "Collection":     (["alloc"],     "passthrough", "none"),
    # IO — fall-through default for write-side IO (print / eprint /
    # putchar / dbg / env_set / env_unset / file_write_* / fs_*
    # mutations / pipe_*). These take an input value and push it
    # to stdout/file/etc; output value (if any) is a status code
    # so taint passthrough is safe. Read-side IO is singled out
    # by PATTERN_OVERRIDES with `propagates` taint.
    "IO":             (["io"],        "passthrough", "io_capability_required"),
    # DataCodec — fall-through default for the encoders/decoders/
    # parsers that allocate output buffers but don't otherwise
    # touch the OS. Pure hash helpers and TOML lookups + I/O parse
    # variants are singled out by NAME_OVERRIDES / PATTERN_OVERRIDES.
    "DataCodec":      (["alloc"],     "passthrough", "none"),
}


def fmt_abi(ir_decl):
    if not ir_decl:
        return "TODO"
    ret, args = ir_decl
    args_str = ", ".join(args) if args else ""
    return f"({args_str}) -> {ret}"


# ---------- Main ----------

def main():
    src = S1.read_text(encoding="utf-8", errors="replace")

    rt_pairs = parse_get_rt_name(src)            # (name, symbol)
    void_set = parse_is_void_ret(src)
    ptr_ret_set = parse_is_ptr_ret(src)
    ir = parse_ir_declares(src)                  # symbol -> (ret, args)
    rt_defs = collect_runtime_defs()

    # Deduplicate by symbol — many short names map to the same symbol
    by_symbol = {}
    for name, symbol in rt_pairs:
        if symbol not in by_symbol:
            by_symbol[symbol] = name
        # else: keep first short name; alternatives are aliases

    # Add IR-only entries (symbols declared but with no get_rt_name mapping
    # — usually generated from macro expansion or referenced internally).
    for sym in sorted(ir.keys()):
        if sym not in by_symbol:
            short = sym[len("__nucleor_"):]
            by_symbol[sym] = short

    # ---- Classify and emit ----
    rows = []
    for sym, name in by_symbol.items():
        cls = classify(name)
        ir_decl = ir.get(sym)
        defined = sym in rt_defs
        intentional = sym in INTENTIONAL_PLACEHOLDER

        # Stability:
        #   stable        — defined in runtime
        #   unstable      — declared but intentionally placeholder for v0.4
        #   experimental  — declared but no plan; potential bug (REVIEW REQUIRED)
        if defined:
            stability = "stable"
        elif intentional:
            stability = "unstable"
        else:
            stability = "experimental"

        notes_bits = []
        if not defined and intentional:
            notes_bits.append("intentional v0.4 placeholder; declared in IR for forward compat, runtime body deferred")
        elif not defined:
            notes_bits.append("declared in IR but no __nucleor_* definition found in stdlib/runtime/*.c (REVIEW REQUIRED)")
        if cls == "Unclassified":
            notes_bits.append("name pattern did not match any class rule (REVIEW REQUIRED)")

        # Resolution order: NAME_OVERRIDES → PATTERN_OVERRIDES →
        # CLASS_DEFAULTS → TODO sentinel.
        resolved = NAME_OVERRIDES.get(name)
        if resolved is None:
            for pat, vals in PATTERN_OVERRIDES:
                if pat.match(name):
                    resolved = vals
                    break
        if resolved is None:
            resolved = CLASS_DEFAULTS.get(cls)

        if resolved is not None:
            eff_list, taint_val, proof_val = resolved
            # Render effects as a TOML array literal. Empty list is
            # the explicit no-effect signal (PureMath); non-empty
            # lists list each effect string.
            if not eff_list:
                effects_field = "[]"
            else:
                effects_field = "[" + ", ".join(f'"{e}"' for e in eff_list) + "]"
        else:
            effects_field = "TODO"
            taint_val = "TODO"
            proof_val = "TODO"

        rows.append({
            "name": name,
            "class": cls,
            "symbol": sym,
            "dispatch": "RuntimeCall",
            "abi": fmt_abi(ir_decl),
            "effects": effects_field,
            "taint": taint_val,
            "units": "passthrough",
            "proof_obligation": proof_val,
            "stability": stability,
            "since": SINCE_MAP.get(name, "0.1.0"),
            "notes": "; ".join(notes_bits),
        })

    rows.sort(key=lambda r: (r["class"], r["name"]))

    # ---- Build REVIEW REQUIRED list ----
    review = [r for r in rows if "REVIEW REQUIRED" in r["notes"]]

    # ---- Emit ----
    out_lines = []
    out_lines.append("# helper_manifest.toml")
    out_lines.append("#")
    out_lines.append("# Source-of-truth schema map for every helper in the Nucleor_OSS")
    out_lines.append("# project. Generated by tools/gen_helper_manifest.py from the")
    out_lines.append("# canonical compiler ABI tables and runtime C source. Do not edit")
    out_lines.append("# by hand — re-run the generator after adding any helper.")
    out_lines.append("#")
    out_lines.append("# Schema: see docs/rfcs/helper_manifest_schema.md")
    out_lines.append("# Contract: see docs/rfcs/HELPER-CONTRACT.md")
    out_lines.append(f"# Total helpers: {len(rows)}")
    out_lines.append(f"# Of which REVIEW REQUIRED: {len(review)}")
    out_lines.append("")

    # ---- REVIEW REQUIRED block ----
    out_lines.append("# ============================================================")
    out_lines.append("# REVIEW REQUIRED")
    out_lines.append("# ============================================================")
    out_lines.append("# These helpers need a human pass before their rows below can be")
    out_lines.append("# considered authoritative. Two reasons trigger inclusion:")
    out_lines.append("#  1. Declared in IR but no __nucleor_* definition found in the")
    out_lines.append("#     runtime (latent linker gap from earlier eras OR the symbol")
    out_lines.append("#     is generated by a runtime macro the regex didn't match).")
    out_lines.append("#  2. Name pattern didn't match any class rule (Unclassified).")
    out_lines.append("# Each row is still emitted below with `stability = \"experimental\"`")
    out_lines.append("# or `class = \"Unclassified\"` so callers can find them.")
    out_lines.append("#")
    for r in review:
        bits = []
        if r["class"] == "Unclassified":
            bits.append("Unclassified")
        if r["stability"] == "experimental":
            bits.append("undefined")
        flag = ", ".join(bits)
        out_lines.append(f"#   {r['name']:<40s} ({flag})")
    out_lines.append("")

    # ---- Helper rows ----
    last_class = None
    for r in rows:
        if r["class"] != last_class:
            out_lines.append("")
            out_lines.append(f"# ----- class: {r['class']} -----")
            out_lines.append("")
            last_class = r["class"]

        out_lines.append("[[helper]]")
        out_lines.append(f'name             = "{r["name"]}"')
        out_lines.append(f'class            = "{r["class"]}"')
        out_lines.append(f'symbol           = "{r["symbol"]}"')
        out_lines.append(f'dispatch         = "{r["dispatch"]}"')
        out_lines.append(f'abi              = "{r["abi"]}"')
        # Effects field is either a TOML array literal (any string
        # starting with '[') or the "TODO" sentinel for classes the
        # generator hasn't yet populated.
        if r["effects"].startswith("["):
            out_lines.append(f'effects          = {r["effects"]}')
        else:
            out_lines.append(f'effects          = "{r["effects"]}"  # TODO')
        if r["taint"] == "TODO":
            out_lines.append(f'taint            = "{r["taint"]}"  # verify before use')
        else:
            out_lines.append(f'taint            = "{r["taint"]}"')
        out_lines.append(f'units            = "{r["units"]}"')
        if r["proof_obligation"] == "TODO":
            out_lines.append(f'proof_obligation = "{r["proof_obligation"]}"  # verify before use')
        else:
            out_lines.append(f'proof_obligation = "{r["proof_obligation"]}"')
        out_lines.append(f'stability        = "{r["stability"]}"')
        out_lines.append(f'since            = "{r["since"]}"')
        if r["notes"]:
            out_lines.append(f'notes            = "{r["notes"]}"')
        else:
            out_lines.append('notes            = ""')
        out_lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out_lines), encoding="utf-8")

    print(f"Wrote {OUT}")
    print(f"Total helpers: {len(rows)}")
    print(f"REVIEW REQUIRED: {len(review)}")
    klass_counts = {}
    for r in rows:
        klass_counts[r["class"]] = klass_counts.get(r["class"], 0) + 1
    for k, v in sorted(klass_counts.items(), key=lambda kv: -kv[1]):
        print(f"  {k:<20s} {v}")


if __name__ == "__main__":
    main()
